-- MySQL Script generated by MySQL Workbench
-- Tue Dec  6 19:16:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProyectoRestaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProyectoRestaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoRestaurante` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ProyectoRestaurante` ;

-- -----------------------------------------------------
-- Table `ProyectoRestaurante`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoRestaurante`.`Cliente` (
  `identidadCliente` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`identidadCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRestaurante`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoRestaurante`.`factura` (
  `Id` VARCHAR(20) NOT NULL,
  `IdentidadCliente` VARCHAR(20) NULL DEFAULT NULL,
  `Cliente` VARCHAR(45) NULL DEFAULT NULL,
  `Fecha` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `FK_Cliente_factura`
    FOREIGN KEY ()
    REFERENCES `ProyectoRestaurante`.`Cliente` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ProyectoRestaurante`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoRestaurante`.`Menu` (
  `CodigoMenu` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(40) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Precio` DECIMAL(18,2) NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`CodigoMenu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ProyectoRestaurante`.`detallefactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoRestaurante`.`detallefactura` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdFactura` INT NULL DEFAULT NULL,
  `CodigoMenu` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `Cantidad` INT NULL DEFAULT NULL,
  `Precio` DECIMAL(10,0) NULL DEFAULT NULL,
  `Sub Total` DECIMAL(10,0) NULL,
  `ISV` DECIMAL(10,0) NULL,
  `Total` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_detalleFactura_pedidos_idx` (`IdFactura` ASC) VISIBLE,
  INDEX `FK_detalleFactura_producto_idx` (`CodigoMenu` ASC) VISIBLE,
  CONSTRAINT `FK_detalleFactura_factura`
    FOREIGN KEY (`IdFactura`)
    REFERENCES `ProyectoRestaurante`.`factura` (`Id`),
  CONSTRAINT `FK_detalleFactura_producto`
    FOREIGN KEY (`CodigoMenu`)
    REFERENCES `ProyectoRestaurante`.`Menu` (`CodigoMenu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ProyectoRestaurante`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoRestaurante`.`usuario` (
  `CodigoUsuario` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(15) NULL DEFAULT NULL,
  `Clave` VARCHAR(45) NULL DEFAULT NULL,
  `EstaActivo` TINYINT NOT NULL,
  PRIMARY KEY (`CodigoUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
